// <auto-generated />
using System;
using CryptoExchangeImporter.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoExchangeImporter.Infrastructure.Migrations
{
    [DbContext(typeof(ExchangeDbContext))]
    partial class ExchangeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CryptoExchangeImporter.Domain.Entities.AvailableFunds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Crypto")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Euro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ExchangeId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeId")
                        .IsUnique();

                    b.ToTable("AvailableFunds", (string)null);
                });

            modelBuilder.Entity("CryptoExchangeImporter.Domain.Entities.Exchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExchangeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeId")
                        .IsUnique()
                        .HasDatabaseName("IX_Exchanges_ExchangeId");

                    b.ToTable("Exchanges", (string)null);
                });

            modelBuilder.Entity("CryptoExchangeImporter.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderBookEntryId")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("OrderBookEntryId")
                        .IsUnique();

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("IX_Orders_OrderId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("CryptoExchangeImporter.Domain.Entities.OrderBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExchangeId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeId")
                        .IsUnique();

                    b.ToTable("OrderBooks", (string)null);
                });

            modelBuilder.Entity("CryptoExchangeImporter.Domain.Entities.OrderBookEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsBid")
                        .HasColumnType("bit");

                    b.Property<int>("OrderBookId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderBookId");

                    b.ToTable("OrderBookEntries", (string)null);
                });

            modelBuilder.Entity("CryptoExchangeImporter.Domain.Entities.AvailableFunds", b =>
                {
                    b.HasOne("CryptoExchangeImporter.Domain.Entities.Exchange", "Exchange")
                        .WithOne("AvailableFunds")
                        .HasForeignKey("CryptoExchangeImporter.Domain.Entities.AvailableFunds", "ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("CryptoExchangeImporter.Domain.Entities.Order", b =>
                {
                    b.HasOne("CryptoExchangeImporter.Domain.Entities.OrderBookEntry", "OrderBookEntry")
                        .WithOne("Order")
                        .HasForeignKey("CryptoExchangeImporter.Domain.Entities.Order", "OrderBookEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderBookEntry");
                });

            modelBuilder.Entity("CryptoExchangeImporter.Domain.Entities.OrderBook", b =>
                {
                    b.HasOne("CryptoExchangeImporter.Domain.Entities.Exchange", "Exchange")
                        .WithOne("OrderBook")
                        .HasForeignKey("CryptoExchangeImporter.Domain.Entities.OrderBook", "ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("CryptoExchangeImporter.Domain.Entities.OrderBookEntry", b =>
                {
                    b.HasOne("CryptoExchangeImporter.Domain.Entities.OrderBook", "OrderBook")
                        .WithMany()
                        .HasForeignKey("OrderBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderBook");
                });

            modelBuilder.Entity("CryptoExchangeImporter.Domain.Entities.Exchange", b =>
                {
                    b.Navigation("AvailableFunds")
                        .IsRequired();

                    b.Navigation("OrderBook")
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoExchangeImporter.Domain.Entities.OrderBookEntry", b =>
                {
                    b.Navigation("Order")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
